name: push-hugo-support

on:
  workflow_dispatch:

jobs:
  hugo-support:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_FLUXCD_USER }}
          password: ${{ secrets.DOCKER_FLUXCD_PASSWORD }}
      -
        name: Checkout repo
        uses: actions/checkout@v3
      -
        name: Set repo_owner variable
        run: make --silent print-repo-owner >> $GITHUB_ENV
      -
        name: Set hugo_version variable
        run: make --silent print-hugo-version >> $GITHUB_ENV
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            HUGO_VERSION=${{ env.hugo_version }}
          tags: ${{ env.repo_owner }}/website:hugo-support
